## Exercise on wine dataset


Let's start off by following the general workflow that we use when moving data into a DataFrame: 

    * Importing Pandas
    * Reading data into the DataFrame
    * Getting a general sense of the data

So, in terms of what you should do for this part...

1. Select the first 10 rows of the `chlorides` column. 
2. Select the last 10 rows of the `chlorides` column. 
3. Select columns `chlorides` **and** `density`. 
4. Select all rows where the `chlorides` value is less than 0.10. 
5. Now select all the rows where the `chlorides` value is greater than the column's mean (try **not** to use a hard-coded value for the mean, but instead a method).
6. Select all those rows where the `pH` is greater than 3.0 and less than 3.5. Further filter the results from 6 to grab only those rows that have a `residual sugar` less than 2.0. 

If you'd like some extra practice, try answering each of the questions in more than one way (because remember, we can often select data in a couple of different ways). Selecting is the same as displaying on the screen in this context.

In [1]:
import pandas as pd

In [2]:
winequality_red = pd.read_csv('../data/winequality-red.csv', sep=";")
winequality_red

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [3]:
#1. Select the first 10 rows of the `chlorides` column. 

winequality_red[['chlorides']].head(10)

   chlorides
0      0.076
1      0.098
2      0.092
3      0.075
4      0.076
5      0.075
6      0.069
7      0.065
8      0.073
9      0.071

In [4]:
#2. Select the last 10 rows of the `chlorides` column. 

winequality_red[['chlorides']].tail(10)

      chlorides
1589      0.073
1590      0.077
1591      0.089
1592      0.076
1593      0.068
1594      0.090
1595      0.062
1596      0.076
1597      0.075
1598      0.067

In [5]:
#3. Select columns `chlorides` and `density`. 

winequality_red[['chlorides', 'density']]

      chlorides  density
0         0.076  0.99780
1         0.098  0.99680
2         0.092  0.99700
3         0.075  0.99800
4         0.076  0.99780
...         ...      ...
1594      0.090  0.99490
1595      0.062  0.99512
1596      0.076  0.99574
1597      0.075  0.99547
1598      0.067  0.99549

[1599 rows x 2 columns]

In [6]:
winequality_red.loc[200:250, ['chlorides', 'density']]

     chlorides  density
200      0.056  0.99695
201      0.097  0.99750
202      0.075  0.99545
203      0.088  0.99610
204      0.089  0.99615
205      0.095  0.99940
206      0.095  0.99940
207      0.069  0.99625
208      0.100  0.99660
209      0.054  0.99800
210      0.039  0.99585
211      0.083  0.99685
212      0.059  0.99800
213      0.060  0.99590
214      0.092  0.99740
215      0.060  0.99740
216      0.101  0.99620
217      0.072  0.99670
218      0.076  0.99570
219      0.080  0.99655
220      0.082  0.99640
221      0.101  0.99570
222      0.057  0.99525
223      0.083  0.99815
224      0.089  0.99745
225      0.073  0.99615
226      0.337  0.99640
227      0.089  0.99840
228      0.073  0.99615
229      0.081  0.99685
230      0.054  0.99270
231      0.078  0.99625
232      0.090  0.99800
233      0.081  0.99685
234      0.065  0.99685
235      0.097  0.99675
236      0.097  0.99675
237      0.097  0.99675
238      0.097  0.99675
239      0.065  0.99685
240      0.263  0.99710
241      0.093  0.99925
242      0.102  0.99565
243      0.075  1.00005
244      0.075  1.00005
245      0.084  0.99830
246      0.075  0.99685
247      0.072  0.99630
248      0.074  0.99615
249      0.084  0.99830
250      0.063  0.99850

In [7]:
winequality_red[['chlorides', 'density']].iloc[200:251]

     chlorides  density
200      0.056  0.99695
201      0.097  0.99750
202      0.075  0.99545
203      0.088  0.99610
204      0.089  0.99615
205      0.095  0.99940
206      0.095  0.99940
207      0.069  0.99625
208      0.100  0.99660
209      0.054  0.99800
210      0.039  0.99585
211      0.083  0.99685
212      0.059  0.99800
213      0.060  0.99590
214      0.092  0.99740
215      0.060  0.99740
216      0.101  0.99620
217      0.072  0.99670
218      0.076  0.99570
219      0.080  0.99655
220      0.082  0.99640
221      0.101  0.99570
222      0.057  0.99525
223      0.083  0.99815
224      0.089  0.99745
225      0.073  0.99615
226      0.337  0.99640
227      0.089  0.99840
228      0.073  0.99615
229      0.081  0.99685
230      0.054  0.99270
231      0.078  0.99625
232      0.090  0.99800
233      0.081  0.99685
234      0.065  0.99685
235      0.097  0.99675
236      0.097  0.99675
237      0.097  0.99675
238      0.097  0.99675
239      0.065  0.99685
240      0.263  0.99710
241      0.093  0.99925
242      0.102  0.99565
243      0.075  1.00005
244      0.075  1.00005
245      0.084  0.99830
246      0.075  0.99685
247      0.072  0.99630
248      0.074  0.99615
249      0.084  0.99830
250      0.063  0.99850

In [8]:
#4. Select all rows where the `chlorides` value is less than 0.10.

winequality_red[winequality_red['chlorides'] < 0.10]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [9]:
#5. Now select all the rows where the `chlorides` value is greater than the column's mean
#(try not to use a hard-coded value for the mean, but instead a method.)

winequality_red[winequality_red['chlorides'] > winequality_red['chlorides'].mean()]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
10,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
12,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.99430,3.58,0.52,9.9,5
13,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1558,6.9,0.630,0.33,6.7,0.235,66.0,115.0,0.99787,3.22,0.56,9.5,5
1570,6.4,0.360,0.53,2.2,0.230,19.0,35.0,0.99340,3.37,0.93,12.4,6
1578,6.8,0.670,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5

In [10]:
winequality_red['chlorides'].mean()

0.08746654158849279

In [11]:
winequality_red.chlorides.mean()

0.08746654158849279

In [12]:
winequality_red.query('chlorides > chlorides.mean()')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
10,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
12,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.99430,3.58,0.52,9.9,5
13,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1558,6.9,0.630,0.33,6.7,0.235,66.0,115.0,0.99787,3.22,0.56,9.5,5
1570,6.4,0.360,0.53,2.2,0.230,19.0,35.0,0.99340,3.37,0.93,12.4,6
1578,6.8,0.670,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5

In [13]:
#6. Select all those rows where the `pH` is greater than 3.0 and less than 3.5. 

winequality_red[winequality_red['pH'].between(3.0, 3.5)]

# donâ€˜t use between with time!

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...
1592,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.60,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1596,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1598,6.0,0.31,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [14]:
#7. Further filter the results from 6 to grab only those rows that have a `residual sugar` less than 2.0.
#Tip: Use backticks (``) to mask column names with spaces in query string.

winequality_red[winequality_red['pH'].between(3.0, 3.5) & (winequality_red['residual sugar'] < 2.0)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
10,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1569,6.2,0.51,0.14,1.9,0.056,15.0,34.0,0.99396,3.48,0.57,11.5,6
1576,8.0,0.30,0.63,1.6,0.081,16.0,29.0,0.99588,3.30,0.78,10.8,6
1578,6.8,0.67,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1590,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6

In [15]:
winequality_red[winequality_red['pH'].between(3.0, 3.5)].query('`residual sugar` < 2.0')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
10,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1569,6.2,0.51,0.14,1.9,0.056,15.0,34.0,0.99396,3.48,0.57,11.5,6
1576,8.0,0.30,0.63,1.6,0.081,16.0,29.0,0.99588,3.30,0.78,10.8,6
1578,6.8,0.67,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1590,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6

## Exercise on iris dataset

![IRIS, https://github.com/simonava5/fishers-iris-data](../images/iris.png)

After the notebook with a lot of new input, let's start applying it totally by yourselves. 
For this purpose we will use one of the most standard real-life datasets: It's called Iris Dataset, and is all about the plant iris. Let's learn a little bit more about the dataset by taking a closer look at it.

In [16]:
# import pandas
import pandas as pd

In [17]:
# load the data
iris = pd.read_csv('../../Data/iris.csv')
iris

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [18]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

1. Let us first have a look at the head of the table, maybe also on the last 10 rows...

In [19]:
iris.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [20]:
iris.tail(10)

     sepal_length  sepal_width  petal_length  petal_width         species
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

2. How many irises are the data set?

In [21]:
# 150 different entries, so also 150 irises
len(iris)

150

In [22]:
iris.nunique()

sepal_length    35
sepal_width     23
petal_length    43
petal_width     22
species          3
dtype: int64

In [23]:
iris.shape

(150, 5)

8. Calculate the basic descriptive statistics for all columns of the iris data set using a single command.

In [24]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

12. Add the sum of the sepal width and length as a new column to your data frame.

In [25]:
iris['sepal_sum'] = iris['sepal_length'] + iris['sepal_width']
iris

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_sum
0,5.1,3.5,1.4,0.2,Iris-setosa,8.6
1,4.9,3.0,1.4,0.2,Iris-setosa,7.9
2,4.7,3.2,1.3,0.2,Iris-setosa,7.9
3,4.6,3.1,1.5,0.2,Iris-setosa,7.7
4,5.0,3.6,1.4,0.2,Iris-setosa,8.6
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,9.7
146,6.3,2.5,5.0,1.9,Iris-virginica,8.8
147,6.5,3.0,5.2,2.0,Iris-virginica,9.5
148,6.2,3.4,5.4,2.3,Iris-virginica,9.6
149,5.9,3.0,5.1,1.8,Iris-virginica,8.9

In [26]:
# with the insert-command I can choose where to insert the new column

iris.insert(2, 'sepal_total', iris['sepal_length'] + iris['sepal_width'])
iris

,sepal_length,sepal_width,sepal_total,petal_length,petal_width,species,sepal_sum
0,5.1,3.5,8.6,1.4,0.2,Iris-setosa,8.6
1,4.9,3.0,7.9,1.4,0.2,Iris-setosa,7.9
2,4.7,3.2,7.9,1.3,0.2,Iris-setosa,7.9
3,4.6,3.1,7.7,1.5,0.2,Iris-setosa,7.7
4,5.0,3.6,8.6,1.4,0.2,Iris-setosa,8.6
...,...,...,...,...,...,...,...
145,6.7,3.0,9.7,5.2,2.3,Iris-virginica,9.7
146,6.3,2.5,8.8,5.0,1.9,Iris-virginica,8.8
147,6.5,3.0,9.5,5.2,2.0,Iris-virginica,9.5
148,6.2,3.4,9.6,5.4,2.3,Iris-virginica,9.6
149,5.9,3.0,8.9,5.1,1.8,Iris-virginica,8.9

In [27]:
# reordering the columns

iris["something"] = iris['sepal_length'] + iris['sepal_width']

iris_1 = iris[['sepal_length', 'sepal_width', 'something', 'petal_length', 'petal_width', 'species']]
iris_1

,sepal_length,sepal_width,something,petal_length,petal_width,species
0,5.1,3.5,8.6,1.4,0.2,Iris-setosa
1,4.9,3.0,7.9,1.4,0.2,Iris-setosa
2,4.7,3.2,7.9,1.3,0.2,Iris-setosa
3,4.6,3.1,7.7,1.5,0.2,Iris-setosa
4,5.0,3.6,8.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,6.7,3.0,9.7,5.2,2.3,Iris-virginica
146,6.3,2.5,8.8,5.0,1.9,Iris-virginica
147,6.5,3.0,9.5,5.2,2.0,Iris-virginica
148,6.2,3.4,9.6,5.4,2.3,Iris-virginica
149,5.9,3.0,8.9,5.1,1.8,Iris-virginica

18. Create a new column with a rough estimate of petal area by multiplying petal length and width together.

In [28]:
iris['petal_area'] = iris['petal_length'] * iris['petal_width']
iris

,sepal_length,sepal_width,sepal_total,petal_length,petal_width,species,sepal_sum,something,petal_area
0,5.1,3.5,8.6,1.4,0.2,Iris-setosa,8.6,8.6,0.28
1,4.9,3.0,7.9,1.4,0.2,Iris-setosa,7.9,7.9,0.28
2,4.7,3.2,7.9,1.3,0.2,Iris-setosa,7.9,7.9,0.26
3,4.6,3.1,7.7,1.5,0.2,Iris-setosa,7.7,7.7,0.30
4,5.0,3.6,8.6,1.4,0.2,Iris-setosa,8.6,8.6,0.28
...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,9.7,5.2,2.3,Iris-virginica,9.7,9.7,11.96
146,6.3,2.5,8.8,5.0,1.9,Iris-virginica,8.8,8.8,9.50
147,6.5,3.0,9.5,5.2,2.0,Iris-virginica,9.5,9.5,10.40
148,6.2,3.4,9.6,5.4,2.3,Iris-virginica,9.6,9.6,12.42
149,5.9,3.0,8.9,5.1,1.8,Iris-virginica,8.9,8.9,9.18

19. Create a new dataframe with petal areas greater than $1cm^2$.

In [29]:
iris_great_petal = iris[iris['petal_area'] > 1]
iris_great_petal

,sepal_length,sepal_width,sepal_total,petal_length,petal_width,species,sepal_sum,something,petal_area
50,7.0,3.2,10.2,4.7,1.4,Iris-versicolor,10.2,10.2,6.58
51,6.4,3.2,9.6,4.5,1.5,Iris-versicolor,9.6,9.6,6.75
52,6.9,3.1,10.0,4.9,1.5,Iris-versicolor,10.0,10.0,7.35
53,5.5,2.3,7.8,4.0,1.3,Iris-versicolor,7.8,7.8,5.20
54,6.5,2.8,9.3,4.6,1.5,Iris-versicolor,9.3,9.3,6.90
...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,9.7,5.2,2.3,Iris-virginica,9.7,9.7,11.96
146,6.3,2.5,8.8,5.0,1.9,Iris-virginica,8.8,8.8,9.50
147,6.5,3.0,9.5,5.2,2.0,Iris-virginica,9.5,9.5,10.40
148,6.2,3.4,9.6,5.4,2.3,Iris-virginica,9.6,9.6,12.42
149,5.9,3.0,8.9,5.1,1.8,Iris-virginica,8.9,8.9,9.18

In [30]:
iris

,sepal_length,sepal_width,sepal_total,petal_length,petal_width,species,sepal_sum,something,petal_area
0,5.1,3.5,8.6,1.4,0.2,Iris-setosa,8.6,8.6,0.28
1,4.9,3.0,7.9,1.4,0.2,Iris-setosa,7.9,7.9,0.28
2,4.7,3.2,7.9,1.3,0.2,Iris-setosa,7.9,7.9,0.26
3,4.6,3.1,7.7,1.5,0.2,Iris-setosa,7.7,7.7,0.30
4,5.0,3.6,8.6,1.4,0.2,Iris-setosa,8.6,8.6,0.28
...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,9.7,5.2,2.3,Iris-virginica,9.7,9.7,11.96
146,6.3,2.5,8.8,5.0,1.9,Iris-virginica,8.8,8.8,9.50
147,6.5,3.0,9.5,5.2,2.0,Iris-virginica,9.5,9.5,10.40
148,6.2,3.4,9.6,5.4,2.3,Iris-virginica,9.6,9.6,12.42
149,5.9,3.0,8.9,5.1,1.8,Iris-virginica,8.9,8.9,9.18

In [34]:
id(iris['sepal_length']) # this is the address - so one can compare the adresses of different DataFrames or Columns

4543456688

20. Using the original unfiltered dataframe, create 3 new dataframes, each containing only irises of each a single species 'Iris-setosa', 'Iris-versicolor' or 'Iris-virginica'.

In [31]:
iris_setosa = iris[iris['species'] == 'Iris-setosa']
iris_setosa

,sepal_length,sepal_width,sepal_total,petal_length,petal_width,species,sepal_sum,something,petal_area
0,5.1,3.5,8.6,1.4,0.2,Iris-setosa,8.6,8.6,0.28
1,4.9,3.0,7.9,1.4,0.2,Iris-setosa,7.9,7.9,0.28
2,4.7,3.2,7.9,1.3,0.2,Iris-setosa,7.9,7.9,0.26
3,4.6,3.1,7.7,1.5,0.2,Iris-setosa,7.7,7.7,0.30
4,5.0,3.6,8.6,1.4,0.2,Iris-setosa,8.6,8.6,0.28
5,5.4,3.9,9.3,1.7,0.4,Iris-setosa,9.3,9.3,0.68
6,4.6,3.4,8.0,1.4,0.3,Iris-setosa,8.0,8.0,0.42
7,5.0,3.4,8.4,1.5,0.2,Iris-setosa,8.4,8.4,0.30
8,4.4,2.9,7.3,1.4,0.2,Iris-setosa,7.3,7.3,0.28
9,4.9,3.1,8.0,1.5,0.1,Iris-setosa,8.0,8.0,0.15
10,5.4,3.7,9.1,1.5,0.2,Iris-setosa,9.1,9.1,0.30
11,4.8,3.4,8.2,1.6,0.2,Iris-setosa,8.2,8.2,0.32
12,4.8,3.0,7.8,1.4,0.1,Iris-setosa,7.8,7.8,0.14
13,4.3,3.0,7.3,1.1,0.1,Iris-setosa,7.3,7.3,0.11
14,5.8,4.0,9.8,1.2,0.2,Iris-setosa,9.8,9.8,0.24
15,5.7,4.4,10.1,1.5,0.4,Iris-setosa,10.1,10.1,0.60
16,5.4,3.9,9.3,1.3,0.4,Iris-setosa,9.3,9.3,0.52
17,5.1,3.5,8.6,1.4,0.3,Iris-setosa,8.6,8.6,0.42
18,5.7,3.8,9.5,1.7,0.3,Iris-setosa,9.5,9.5,0.51
19,5.1,3.8,8.9,1.5,0.3,Iris-setosa,8.9,8.9,0.45
20,5.4,3.4,8.8,1.7,0.2,Iris-setosa,8.8,8.8,0.34
21,5.1,3.7,8.8,1.5,0.4,Iris-setosa,8.8,8.8,0.60
22,4.6,3.6,8.2,1.0,0.2,Iris-setosa,8.2,8.2,0.20
23,5.1,3.3,8.4,1.7,0.5,Iris-setosa,8.4,8.4,0.85
24,4.8,3.4,8.2,1.9,0.2,Iris-setosa,8.2,8.2,0.38
25,5.0,3.0,8.0,1.6,0.2,Iris-setosa,8.0,8.0,0.32
26,5.0,3.4,8.4,1.6,0.4,Iris-setosa,8.4,8.4,0.64
27,5.2,3.5,8.7,1.5,0.2,Iris-setosa,8.7,8.7,0.30
28,5.2,3.4,8.6,1.4,0.2,Iris-setosa,8.6,8.6,0.28
29,4.7,3.2,7.9,1.6,0.2,Iris-setosa,7.9,7.9,0.32
30,4.8,3.1,7.9,1.6,0.2,Iris-setosa,7.9,7.9,0.32
31,5.4,3.4,8.8,1.5,0.4,Iris-setosa,8.8,8.8,0.60
32,5.2,4.1,9.3,1.5,0.1,Iris-setosa,9.3,9.3,0.15
33,5.5,4.2,9.7,1.4,0.2,Iris-setosa,9.7,9.7,0.28
34,4.9,3.1,8.0,1.5,0.1,Iris-setosa,8.0,8.0,0.15
35,5.0,3.2,8.2,1.2,0.2,Iris-setosa,8.2,8.2,0.24
36,5.5,3.5,9.0,1.3,0.2,Iris-setosa,9.0,9.0,0.26
37,4.9,3.1,8.0,1.5,0.1,Iris-setosa,8.0,8.0,0.15
38,4.4,3.0,7.4,1.3,0.2,Iris-setosa,7.4,7.4,0.26
39,5.1,3.4,8.5,1.5,0.2,Iris-setosa,8.5,8.5,0.30
40,5.0,3.5,8.5,1.3,0.3,Iris-setosa,8.5,8.5,0.39
41,4.5,2.3,6.8,1.3,0.3,Iris-setosa,6.8,6.8,0.39
42,4.4,3.2,7.6,1.3,0.2,Iris-setosa,7.6,7.6,0.26
43,5.0,3.5,8.5,1.6,0.6,Iris-setosa,8.5,8.5,0.96
44,5.1,3.8,8.9,1.9,0.4,Iris-setosa,8.9,8.9,0.76
45,4.8,3.0,7.8,1.4,0.3,Iris-setosa,7.8,7.8,0.42
46,5.1,3.8,8.9,1.6,0.2,Iris-setosa,8.9,8.9,0.32
47,4.6,3.2,7.8,1.4,0.2,Iris-setosa,7.8,7.8,0.28
48,5.3,3.7,9.0,1.5,0.2,Iris-setosa,9.0,9.0,0.30
49,5.0,3.3,8.3,1.4,0.2,Iris-setosa,8.3,8.3,0.28

In [32]:
iris_versicolor = iris[iris['species'] == 'Iris-versicolor']
iris_versicolor

,sepal_length,sepal_width,sepal_total,petal_length,petal_width,species,sepal_sum,something,petal_area
50,7.0,3.2,10.2,4.7,1.4,Iris-versicolor,10.2,10.2,6.58
51,6.4,3.2,9.6,4.5,1.5,Iris-versicolor,9.6,9.6,6.75
52,6.9,3.1,10.0,4.9,1.5,Iris-versicolor,10.0,10.0,7.35
53,5.5,2.3,7.8,4.0,1.3,Iris-versicolor,7.8,7.8,5.20
54,6.5,2.8,9.3,4.6,1.5,Iris-versicolor,9.3,9.3,6.90
55,5.7,2.8,8.5,4.5,1.3,Iris-versicolor,8.5,8.5,5.85
56,6.3,3.3,9.6,4.7,1.6,Iris-versicolor,9.6,9.6,7.52
57,4.9,2.4,7.3,3.3,1.0,Iris-versicolor,7.3,7.3,3.30
58,6.6,2.9,9.5,4.6,1.3,Iris-versicolor,9.5,9.5,5.98
59,5.2,2.7,7.9,3.9,1.4,Iris-versicolor,7.9,7.9,5.46
60,5.0,2.0,7.0,3.5,1.0,Iris-versicolor,7.0,7.0,3.50
61,5.9,3.0,8.9,4.2,1.5,Iris-versicolor,8.9,8.9,6.30
62,6.0,2.2,8.2,4.0,1.0,Iris-versicolor,8.2,8.2,4.00
63,6.1,2.9,9.0,4.7,1.4,Iris-versicolor,9.0,9.0,6.58
64,5.6,2.9,8.5,3.6,1.3,Iris-versicolor,8.5,8.5,4.68
65,6.7,3.1,9.8,4.4,1.4,Iris-versicolor,9.8,9.8,6.16
66,5.6,3.0,8.6,4.5,1.5,Iris-versicolor,8.6,8.6,6.75
67,5.8,2.7,8.5,4.1,1.0,Iris-versicolor,8.5,8.5,4.10
68,6.2,2.2,8.4,4.5,1.5,Iris-versicolor,8.4,8.4,6.75
69,5.6,2.5,8.1,3.9,1.1,Iris-versicolor,8.1,8.1,4.29
70,5.9,3.2,9.1,4.8,1.8,Iris-versicolor,9.1,9.1,8.64
71,6.1,2.8,8.9,4.0,1.3,Iris-versicolor,8.9,8.9,5.20
72,6.3,2.5,8.8,4.9,1.5,Iris-versicolor,8.8,8.8,7.35
73,6.1,2.8,8.9,4.7,1.2,Iris-versicolor,8.9,8.9,5.64
74,6.4,2.9,9.3,4.3,1.3,Iris-versicolor,9.3,9.3,5.59
75,6.6,3.0,9.6,4.4,1.4,Iris-versicolor,9.6,9.6,6.16
76,6.8,2.8,9.6,4.8,1.4,Iris-versicolor,9.6,9.6,6.72
77,6.7,3.0,9.7,5.0,1.7,Iris-versicolor,9.7,9.7,8.50
78,6.0,2.9,8.9,4.5,1.5,Iris-versicolor,8.9,8.9,6.75
79,5.7,2.6,8.3,3.5,1.0,Iris-versicolor,8.3,8.3,3.50
80,5.5,2.4,7.9,3.8,1.1,Iris-versicolor,7.9,7.9,4.18
81,5.5,2.4,7.9,3.7,1.0,Iris-versicolor,7.9,7.9,3.70
82,5.8,2.7,8.5,3.9,1.2,Iris-versicolor,8.5,8.5,4.68
83,6.0,2.7,8.7,5.1,1.6,Iris-versicolor,8.7,8.7,8.16
84,5.4,3.0,8.4,4.5,1.5,Iris-versicolor,8.4,8.4,6.75
85,6.0,3.4,9.4,4.5,1.6,Iris-versicolor,9.4,9.4,7.20
86,6.7,3.1,9.8,4.7,1.5,Iris-versicolor,9.8,9.8,7.05
87,6.3,2.3,8.6,4.4,1.3,Iris-versicolor,8.6,8.6,5.72
88,5.6,3.0,8.6,4.1,1.3,Iris-versicolor,8.6,8.6,5.33
89,5.5,2.5,8.0,4.0,1.3,Iris-versicolor,8.0,8.0,5.20
90,5.5,2.6,8.1,4.4,1.2,Iris-versicolor,8.1,8.1,5.28
91,6.1,3.0,9.1,4.6,1.4,Iris-versicolor,9.1,9.1,6.44
92,5.8,2.6,8.4,4.0,1.2,Iris-versicolor,8.4,8.4,4.80
93,5.0,2.3,7.3,3.3,1.0,Iris-versicolor,7.3,7.3,3.30
94,5.6,2.7,8.3,4.2,1.3,Iris-versicolor,8.3,8.3,5.46
95,5.7,3.0,8.7,4.2,1.2,Iris-versicolor,8.7,8.7,5.04
96,5.7,2.9,8.6,4.2,1.3,Iris-versicolor,8.6,8.6,5.46
97,6.2,2.9,9.1,4.3,1.3,Iris-versicolor,9.1,9.1,5.59
98,5.1,2.5,7.6,3.0,1.1,Iris-versicolor,7.6,7.6,3.30
99,5.7,2.8,8.5,4.1,1.3,Iris-versicolor,8.5,8.5,5.33

In [33]:
iris_virginica = iris[iris['species'] == 'Iris-virginica']
iris_virginica

,sepal_length,sepal_width,sepal_total,petal_length,petal_width,species,sepal_sum,something,petal_area
100,6.3,3.3,9.6,6.0,2.5,Iris-virginica,9.6,9.6,15.00
101,5.8,2.7,8.5,5.1,1.9,Iris-virginica,8.5,8.5,9.69
102,7.1,3.0,10.1,5.9,2.1,Iris-virginica,10.1,10.1,12.39
103,6.3,2.9,9.2,5.6,1.8,Iris-virginica,9.2,9.2,10.08
104,6.5,3.0,9.5,5.8,2.2,Iris-virginica,9.5,9.5,12.76
105,7.6,3.0,10.6,6.6,2.1,Iris-virginica,10.6,10.6,13.86
106,4.9,2.5,7.4,4.5,1.7,Iris-virginica,7.4,7.4,7.65
107,7.3,2.9,10.2,6.3,1.8,Iris-virginica,10.2,10.2,11.34
108,6.7,2.5,9.2,5.8,1.8,Iris-virginica,9.2,9.2,10.44
109,7.2,3.6,10.8,6.1,2.5,Iris-virginica,10.8,10.8,15.25
110,6.5,3.2,9.7,5.1,2.0,Iris-virginica,9.7,9.7,10.20
111,6.4,2.7,9.1,5.3,1.9,Iris-virginica,9.1,9.1,10.07
112,6.8,3.0,9.8,5.5,2.1,Iris-virginica,9.8,9.8,11.55
113,5.7,2.5,8.2,5.0,2.0,Iris-virginica,8.2,8.2,10.00
114,5.8,2.8,8.6,5.1,2.4,Iris-virginica,8.6,8.6,12.24
115,6.4,3.2,9.6,5.3,2.3,Iris-virginica,9.6,9.6,12.19
116,6.5,3.0,9.5,5.5,1.8,Iris-virginica,9.5,9.5,9.90
117,7.7,3.8,11.5,6.7,2.2,Iris-virginica,11.5,11.5,14.74
118,7.7,2.6,10.3,6.9,2.3,Iris-virginica,10.3,10.3,15.87
119,6.0,2.2,8.2,5.0,1.5,Iris-virginica,8.2,8.2,7.50
120,6.9,3.2,10.1,5.7,2.3,Iris-virginica,10.1,10.1,13.11
121,5.6,2.8,8.4,4.9,2.0,Iris-virginica,8.4,8.4,9.80
122,7.7,2.8,10.5,6.7,2.0,Iris-virginica,10.5,10.5,13.40
123,6.3,2.7,9.0,4.9,1.8,Iris-virginica,9.0,9.0,8.82
124,6.7,3.3,10.0,5.7,2.1,Iris-virginica,10.0,10.0,11.97
125,7.2,3.2,10.4,6.0,1.8,Iris-virginica,10.4,10.4,10.80
126,6.2,2.8,9.0,4.8,1.8,Iris-virginica,9.0,9.0,8.64
127,6.1,3.0,9.1,4.9,1.8,Iris-virginica,9.1,9.1,8.82
128,6.4,2.8,9.2,5.6,2.1,Iris-virginica,9.2,9.2,11.76
129,7.2,3.0,10.2,5.8,1.6,Iris-virginica,10.2,10.2,9.28
130,7.4,2.8,10.2,6.1,1.9,Iris-virginica,10.2,10.2,11.59
131,7.9,3.8,11.7,6.4,2.0,Iris-virginica,11.7,11.7,12.80
132,6.4,2.8,9.2,5.6,2.2,Iris-virginica,9.2,9.2,12.32
133,6.3,2.8,9.1,5.1,1.5,Iris-virginica,9.1,9.1,7.65
134,6.1,2.6,8.7,5.6,1.4,Iris-virginica,8.7,8.7,7.84
135,7.7,3.0,10.7,6.1,2.3,Iris-virginica,10.7,10.7,14.03
136,6.3,3.4,9.7,5.6,2.4,Iris-virginica,9.7,9.7,13.44
137,6.4,3.1,9.5,5.5,1.8,Iris-virginica,9.5,9.5,9.90
138,6.0,3.0,9.0,4.8,1.8,Iris-virginica,9.0,9.0,8.64
139,6.9,3.1,10.0,5.4,2.1,Iris-virginica,10.0,10.0,11.34
140,6.7,3.1,9.8,5.6,2.4,Iris-virginica,9.8,9.8,13.44
141,6.9,3.1,10.0,5.1,2.3,Iris-virginica,10.0,10.0,11.73
142,5.8,2.7,8.5,5.1,1.9,Iris-virginica,8.5,8.5,9.69
143,6.8,3.2,10.0,5.9,2.3,Iris-virginica,10.0,10.0,13.57
144,6.7,3.3,10.0,5.7,2.5,Iris-virginica,10.0,10.0,14.25
145,6.7,3.0,9.7,5.2,2.3,Iris-virginica,9.7,9.7,11.96
146,6.3,2.5,8.8,5.0,1.9,Iris-virginica,8.8,8.8,9.50
147,6.5,3.0,9.5,5.2,2.0,Iris-virginica,9.5,9.5,10.40
148,6.2,3.4,9.6,5.4,2.3,Iris-virginica,9.6,9.6,12.42
149,5.9,3.0,8.9,5.1,1.8,Iris-virginica,8.9,8.9,9.18